before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: QEY++qY0DwhXkGTFTivOM/8JZTUw/n5cDgscGhxEZ0X0EYMOlhAselnh3xv5OTCIl6F+EphTgnvMC2B8z6UhrH3fsQFadigNsEgFNySFgINK7iDS0LklRqgBXVPOYdzTwAJR0ot686WdzJMo+3h1ARvmV0auoqr8kLfxbXf30U2wmRnuvaS7fxzaqBGJCerlr5RPVSGIMLWGI6HeOEDErDbfE2N9tJaKicuhJER0C5m7axTghcGB8nVDEpiZCr99uhzUAenhO4yUk1BXmLNsc30s21kG4aIe6gBuD8q+fj37ShQToXFyEJ/sv1bQ8oqrQchs3ES+eUL2PS/vy99icMMxdvYBKv5x3jOSsj7nBChCJSTbkmWhHnk1/oDWN1ZWAap2uOr+owMHbFKonFW0g+PG7LPYh7a3uZbpJ17y0I16WXOMS8SgXLGglg5Qsm11Y7hYQ139Fz8Q03oTBhwucSnUUWvoRwtJrFQl6/TK+8/vrtw6pzZqdwg5spC7XgEvRVYcJhH92L+m8na1hRHmW6pBbVcyJPzETYyF9xhmjGTRwo22qS6kTePtG5I9zOQlClQKEbaG8vq/W+kVqGIJlTG7G+jXYilqK1rNvxnE4Aaa2YNGwbLjsknXEFiInrsyX31rI479lZ9lSDwzKpPylGkd+eqNT0aPcoV+TOxByCs= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
